# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bigmoji < Formula
  desc "A helper utility for slicing PNGs into 4x4 grids for Slack Bigmojis."
  homepage "https://github.com/joepurdy/bigmoji/"
  version "1.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/joepurdy/bigmoji/releases/download/v1.0.0/bigmoji_Darwin_all.tar.gz"
    sha256 "2a9edf704233e7a640e01ed4ab68ac288b6c0bde1b762bc3c1f9b93daef14a6e"

    def install
      bin.install "bigmoji"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joepurdy/bigmoji/releases/download/v1.0.0/bigmoji_Linux_x86_64.tar.gz"
        sha256 "762e73fa029565df7f6e21915c68bd78892951f3c14691838232e756d109b8d2"

        def install
          bin.install "bigmoji"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joepurdy/bigmoji/releases/download/v1.0.0/bigmoji_Linux_arm64.tar.gz"
        sha256 "83e0bbaa3f66e8eca85ceb513ec9a7b6027f304ca13c2a4fee4e5a0fac233cb1"

        def install
          bin.install "bigmoji"
        end
      end
    end
  end

  def caveats
    <<~EOS
      You can now use bigmoji to create Slack Bigmojis!
    EOS
  end

  test do
    system "#{bin}/bigmoji --version"
  end
end
