# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bigmoji < Formula
  desc "A helper utility for slicing PNGs into 4x4 grids for Slack Bigmojis."
  homepage "https://github.com/joepurdy/bigmoji/"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/joepurdy/bigmoji/releases/download/v0.0.1/bigmoji_0.0.1_macOS_arm64.tar.gz"
      sha256 "b8d19db3cc151ddbbe436a46af91517faafdaf182136e77c155120afd59e7b93"

      def install
        bin.install "bigmoji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joepurdy/bigmoji/releases/download/v0.0.1/bigmoji_0.0.1_macOS_x86_64.tar.gz"
      sha256 "adf922245df1a5218025b3641aa6b9d80a96df2dc587ff2d6cc26fea1e659ab7"

      def install
        bin.install "bigmoji"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joepurdy/bigmoji/releases/download/v0.0.1/bigmoji_0.0.1_linux_x86_64.tar.gz"
      sha256 "556fbb8c28097a3f3adaaa63a3267153081ed4bbe67253d3a87e922847fd25c1"

      def install
        bin.install "bigmoji"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joepurdy/bigmoji/releases/download/v0.0.1/bigmoji_0.0.1_linux_arm64.tar.gz"
      sha256 "48dba849383ad4dfab172d5ab4378a3d36fcac15d1f5b16d6163deffeb25bb02"

      def install
        bin.install "bigmoji"
      end
    end
  end

  test do
    system "#{bin}/bigmoji --version"
  end
end
